/**
 * Escape-first markdown → HTML for the public note page (`GET /p/:token`).
 *
 * Every character of the note is HTML-entity-escaped BEFORE any markdown
 * transform runs, and every tag in the output is generated by this module —
 * raw HTML in a note renders as visible literal text, the server-side twin of
 * the desktop's drop-don't-render posture. That property is why this file can
 * exist without a renderer/sanitizer dependency, and it is what the tests pin.
 *
 * Deliberately a subset: headings, bold/italic/strikethrough, inline code,
 * fenced code blocks, blockquotes, nested ul/ol, hr, links (https/http/mailto
 * only — anything else stays plain text), images, wikilinks (as inert spans —
 * their targets may be private notes). Unknown markdown degrades to escaped
 * plain text, never to markup.
 */

export interface RenderOptions {
  /**
   * Map an image src from the note to a servable URL, or null to refuse it.
   * Only vault-relative paths are offered (leading `/` already stripped —
   * the desktop embeds `![](/attachments/x.png)` against the vault root);
   * schemeful/absolute/`..` sources are never offered.
   */
  assetUrl: (relPath: string) => string | null;
}

export interface RenderedNote {
  bodyHtml: string;
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
}

/** Strip a leading `---\n…\n---` frontmatter block (must open at char 0). */
export function stripFrontmatter(md: string): string {
  if (!md.startsWith("---\n") && md !== "---") return md;
  const end = md.indexOf("\n---", 3);
  if (end === -1) return md;
  const after = md.indexOf("\n", end + 1);
  return after === -1 ? "" : md.slice(after + 1);
}

/**
 * Vault-relative asset path from an image src, or null. Accepts `attachments/x`
 * and the desktop's `/attachments/x` (one leading slash = vault root); refuses
 * schemes, backslashes, `..` traversal, and empty segments.
 */
export function relAssetPath(src: string): string | null {
  let s = src.trim();
  if (s.startsWith("/")) s = s.slice(1);
  if (s === "" || s.includes("\\") || s.startsWith("/")) return null;
  // A scheme (`http:`, `javascript:`) or a Windows drive can't be a vault path.
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(s)) return null;
  const segments = s.split("/");
  if (segments.some((seg) => seg === "" || seg === "." || seg === "..")) return null;
  return s;
}

const SAFE_LINK_RE = /^(https?:\/\/|mailto:)/i;

/**
 * Inline transforms over ALREADY-ESCAPED text. Code spans are lifted out
 * first so nothing inside them is treated as markdown, then restored last.
 */
function renderInline(escaped: string, opts: RenderOptions): string {
  const stash: string[] = [];
  const keep = (html: string): string => {
    stash.push(html);
    return `\u0000${stash.length - 1}\u0000`;
  };

  let s = escaped;

  // `code` — content stays exactly as escaped, no further transforms inside.
  s = s.replace(/`([^`\n]+)`/g, (_m, code: string) => keep(`<code>${code}</code>`));

  // ![[embedded note or file]] and [[Title|alias]] — inert spans; the target
  // may be a private note, so these never become links.
  s = s.replace(/!?\[\[([^\[\]\n]+)\]\]/g, (_m, inner: string) => {
    const label = inner.split("|").pop()?.trim() || inner.trim();
    return keep(`<span class="wikilink">${label}</span>`);
  });

  // ![alt](src) — vault-relative images become <img> via assetUrl; external
  // images become plain links (rendering them would leak every viewer's IP to
  // the image host); anything else stays literal text.
  s = s.replace(/!\[([^\]\n]*)\]\(([^)\s]+)(?:\s+[^)]*)?\)/g, (m, alt: string, src: string) => {
    const rel = relAssetPath(src);
    if (rel !== null) {
      const url = opts.assetUrl(rel);
      if (url) return keep(`<img src="${esc(url)}" alt="${alt}" loading="lazy" />`);
      return m;
    }
    if (SAFE_LINK_RE.test(src)) {
      return keep(
        `<a href="${src}" rel="noopener noreferrer" target="_blank">${alt || src}</a>`,
      );
    }
    return m;
  });

  // [text](url) — https/http/mailto only; other schemes stay literal text.
  s = s.replace(/\[([^\]\n]+)\]\(([^)\s]+)(?:\s+[^)]*)?\)/g, (m, text: string, url: string) => {
    if (!SAFE_LINK_RE.test(url)) return m;
    return keep(`<a href="${url}" rel="noopener noreferrer" target="_blank">${text}</a>`);
  });

  // Emphasis. Bold before italic so `**x**` isn't eaten as two italics.
  s = s.replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>");
  s = s.replace(/__([^_\n]+)__/g, "<strong>$1</strong>");
  s = s.replace(/\*([^*\n]+)\*/g, "<em>$1</em>");
  s = s.replace(/(^|\W)_([^_\n]+)_(?=\W|$)/g, "$1<em>$2</em>");
  s = s.replace(/~~([^~\n]+)~~/g, "<del>$1</del>");

  return s.replace(/\u0000(\d+)\u0000/g, (_m, i: string) => stash[Number(i)] ?? "");
}

interface ListFrame {
  type: "ul" | "ol";
  indent: number;
}

const LIST_ITEM_RE = /^(\s*)(?:[-*+]|\d+[.)])\s+(.*)$/;
const ORDERED_RE = /^\s*\d+[.)]\s/;

/** `| --- | :---: |` — the row that makes the line above it a table header. */
const TABLE_SEP_RE = /^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$/;

function splitRow(line: string): string[] {
  let cells = line.split("|").map((c) => c.trim());
  // GFM rows usually open and close with a pipe — those outer splits are
  // empty and are frame, not cells.
  if (cells.length > 0 && cells[0] === "") cells = cells.slice(1);
  if (cells.length > 0 && cells[cells.length - 1] === "") cells = cells.slice(0, -1);
  return cells;
}

function columnAligns(sep: string): Array<"left" | "center" | "right"> {
  return splitRow(sep).map((c) => {
    const l = c.startsWith(":");
    const r = c.endsWith(":");
    if (l && r) return "center";
    if (r) return "right";
    return "left";
  });
}

/** Block-level pass over escaped lines. Recursion only for blockquote bodies. */
function renderBlocks(lines: string[], opts: RenderOptions): string {
  const out: string[] = [];
  const listStack: ListFrame[] = [];

  const closeListsTo = (indent: number): void => {
    while (listStack.length > 0 && listStack[listStack.length - 1].indent >= indent) {
      out.push(`</${listStack.pop()!.type}>`);
    }
  };
  const closeAllLists = (): void => closeListsTo(-1);

  let i = 0;
  while (i < lines.length) {
    const line = lines[i];

    // Fenced code — everything inside stays exactly as escaped.
    const fence = /^(```|~~~)/.exec(line.trim());
    if (fence) {
      closeAllLists();
      const marker = fence[1];
      const body: string[] = [];
      i++;
      while (i < lines.length && !lines[i].trim().startsWith(marker)) {
        body.push(lines[i]);
        i++;
      }
      i++; // skip the closing fence (or run off the end of an unclosed one)
      out.push(`<pre><code>${body.join("\n")}</code></pre>`);
      continue;
    }

    if (line.trim() === "") {
      closeAllLists();
      i++;
      continue;
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(line);
    if (heading) {
      closeAllLists();
      const level = heading[1].length;
      out.push(`<h${level}>${renderInline(heading[2], opts)}</h${level}>`);
      i++;
      continue;
    }

    if (/^\s*([-*_])\s*(\1\s*){2,}$/.test(line)) {
      closeAllLists();
      out.push("<hr />");
      i++;
      continue;
    }

    if (line.trimStart().startsWith("&#62;")) {
      closeAllLists();
      const inner: string[] = [];
      while (i < lines.length && lines[i].trimStart().startsWith("&#62;")) {
        inner.push(lines[i].trimStart().replace(/^&#62;\s?/, ""));
        i++;
      }
      out.push(`<blockquote>${renderBlocks(inner, opts)}</blockquote>`);
      continue;
    }

    // GFM table: a pipe row whose NEXT line is the ---|--- separator.
    if (line.includes("|") && i + 1 < lines.length && TABLE_SEP_RE.test(lines[i + 1])) {
      closeAllLists();
      const aligns = columnAligns(lines[i + 1]);
      const cell = (text: string, tag: "th" | "td", col: number): string => {
        const align = aligns[col] ?? "left";
        const style = align === "left" ? "" : ` style="text-align:${align}"`;
        return `<${tag}${style}>${renderInline(text, opts)}</${tag}>`;
      };
      const header = splitRow(line);
      const rows: string[][] = [];
      i += 2;
      while (i < lines.length && lines[i].includes("|") && lines[i].trim() !== "") {
        rows.push(splitRow(lines[i]));
        i++;
      }
      const thead = `<thead><tr>${header.map((h, c) => cell(h, "th", c)).join("")}</tr></thead>`;
      const tbody = rows
        .map((r) => `<tr>${r.map((v, c) => cell(v, "td", c)).join("")}</tr>`)
        .join("");
      // Same shape the app's editor renders: a scroll wrapper so a wide table
      // scrolls here instead of stretching the page.
      out.push(`<div class="md-table"><table>${thead}${tbody ? `<tbody>${tbody}</tbody>` : ""}</table></div>`);
      continue;
    }

    const item = LIST_ITEM_RE.exec(line);
    if (item) {
      const indent = item[1].length;
      const type: "ul" | "ol" = ORDERED_RE.test(line) ? "ol" : "ul";
      const top = listStack[listStack.length - 1];
      if (!top || indent > top.indent) {
        listStack.push({ type, indent });
        out.push(`<${type}>`);
      } else if (indent < top.indent) {
        closeListsTo(indent);
        if (listStack.length === 0 || listStack[listStack.length - 1].type !== type) {
          listStack.push({ type, indent });
          out.push(`<${type}>`);
        }
      } else if (top.type !== type) {
        out.push(`</${listStack.pop()!.type}>`);
        listStack.push({ type, indent });
        out.push(`<${type}>`);
      }
      out.push(`<li>${renderInline(item[2], opts)}</li>`);
      i++;
      continue;
    }

    // Paragraph: consecutive plain lines; single newlines render as breaks
    // (notes treat them as line breaks, and losing them reads as corruption).
    closeAllLists();
    const para: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !/^(#{1,6})\s/.test(lines[i]) &&
      !LIST_ITEM_RE.test(lines[i]) &&
      !lines[i].trimStart().startsWith("&#62;") &&
      !/^(```|~~~)/.test(lines[i].trim()) &&
      !/^\s*([-*_])\s*(\1\s*){2,}$/.test(lines[i]) &&
      !(lines[i].includes("|") && i + 1 < lines.length && TABLE_SEP_RE.test(lines[i + 1]))
    ) {
      para.push(renderInline(lines[i], opts));
      i++;
    }
    out.push(`<p>${para.join("<br />")}</p>`);
  }
  closeAllLists();
  return out.join("\n");
}

export function renderNoteHtml(md: string, opts: RenderOptions): RenderedNote {
  const escaped = esc(
    stripFrontmatter(md).replace(/\r\n/g, "\n").replace(/\u0000/g, ""),
  );
  return { bodyHtml: renderBlocks(escaped.split("\n"), opts) };
}
