import { betterAuth } from "better-auth";
import { APIError } from "better-auth/api";
import { bearer, mcp, organization } from "better-auth/plugins";
import { Algorithm, hash as argonHash, verify as argonVerify } from "@node-rs/argon2";
import pg from "pg";
import { config } from "../config.js";
import { BRAND_NAME } from "../brand.js";
import { canAddMember, canCreateOrganization } from "../billing/entitlements.js";
import { announceMemberJoined } from "../sync/member-events.js";
import { dispatchMail, emailEnabled } from "../email/mailer.js";
import { invitationEmail, resetPasswordEmail, verifyEmailEmail } from "../email/templates.js";

/**
 * Better Auth (spec 04 §1/§2).
 *
 * - email+password with **argon2id** hashing (overrides the built-in scrypt).
 * - server-side sessions (opaque token in the `session` table) for instant revocation.
 * - `bearer` plugin so the desktop client can authenticate with an
 *   `Authorization: Bearer <session-token>` header (token stored in the OS keychain),
 *   in addition to cookies.
 * - `organization` plugin = vaults/teams: owner/admin/member roles + invitations
 *   (48h expiry per spec).
 * - outbound email (issue #99) is opt-in via env (`email/mailer.ts`). When it is
 *   configured, password reset, sign-up verification and invitation emails are
 *   wired below; when it isn't, the hooks are simply absent — Better Auth then
 *   answers 400 to `request-password-reset`, `/api/auth-methods` advertises
 *   nothing, and the desktop hides the controls. Same pattern as Google.
 *
 * Better Auth wraps this raw pg Pool with its Kysely adapter. Column names are
 * camelCase and quoted; migration 001 (generated by @better-auth/cli) matches.
 */

// argon2id (OWASP default). @node-rs/argon2 already defaults to argon2id; we set
// the algorithm explicitly to satisfy the spec's mandate.
const argonOpts = { algorithm: Algorithm.Argon2id } as const;

export const authPool = new pg.Pool({ connectionString: config.databaseUrl });

// Google social sign-in is opt-in: only wired when both creds are present, so a
// self-hosted server without them just omits the provider (the desktop hides
// the button and email+password keeps working).
export const googleEnabled = Boolean(config.googleClientId && config.googleClientSecret);
const socialProviders = googleEnabled
  ? {
      google: {
        clientId: config.googleClientId!,
        clientSecret: config.googleClientSecret!,
      },
    }
  : undefined;

/** Password-reset links live one hour (Better Auth's default, made explicit
 *  because the email and the reset page both state it). */
const RESET_TOKEN_TTL_SECONDS = 60 * 60;

// Decided once at startup, like `googleEnabled`: the environment doesn't
// change under a running server, and a conditional hook is what makes Better
// Auth report "Reset password isn't enabled" instead of pretending to send.
const mailerOn = emailEnabled();

/**
 * Does this org already hold a live invitation for this address? Used to let a
 * re-invite through the seat cap: it REPLACES the pending row (see
 * `cancelPendingInvitationsOnReInvite`), so no new seat is being taken.
 */
async function hasPendingInvitation(organizationId: string, email: string): Promise<boolean> {
  const { rows } = await authPool.query(
    `SELECT 1 FROM invitation
      WHERE "organizationId" = $1 AND lower(email) = lower($2)
        AND status = 'pending' AND "expiresAt" > now()
      LIMIT 1`,
    [organizationId, email],
  );
  return rows.length > 0;
}

export const auth = betterAuth({
  appName: BRAND_NAME,
  database: authPool,
  secret: config.jwtSecret,
  baseURL: config.betterAuthUrl,
  basePath: "/api/auth",
  // The desktop client is a Tauri webview whose Origin isn't the server's
  // baseURL, so it must be trusted explicitly (spec 04 §7 in-app login).
  // `tauri://localhost` is the packaged-app origin (macOS/Linux);
  // `http://tauri.localhost` is Windows; `http://localhost:1420` is `tauri dev`.
  trustedOrigins: [
    config.betterAuthUrl,
    "tauri://localhost",
    "http://tauri.localhost",
    "http://localhost:1420",
  ],
  // Desktop clients authenticate with a bearer token kept in the OS keychain,
  // so the session's sliding refresh only advances when the app actually calls
  // the server. Better Auth's 7-day default therefore logs people out if they
  // don't open the app for a week. Give sessions a 30-day life, refreshed
  // whenever they're a day old, so a returning user stays signed in.
  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // refresh once the session is a day old
  },
  emailAndPassword: {
    enabled: true,
    // No email round-trip is required to sign in, even when email is configured:
    // verification is sent on sign-up (below) and recorded when the link is
    // clicked, but it doesn't gate anything yet — existing accounts were all
    // created without it, and locking them out would be the #99 failure mode
    // in reverse. Flip this once every account has had a chance to verify.
    requireEmailVerification: false,
    password: {
      hash: (password: string) => argonHash(password, argonOpts),
      verify: ({ hash, password }: { hash: string; password: string }) =>
        argonVerify(hash, password),
    },
    ...(mailerOn
      ? {
          // Forgotten password → emailed single-use link to our own branded
          // page (routes/account-pages.ts), which posts the new password back
          // to Better Auth's `reset-password`. We build the URL from the token
          // rather than using Better Auth's `url`, which detours through
          // `/api/auth/reset-password/:token?callbackURL=` first. Better Auth
          // answers the request neutrally whether or not the account exists,
          // so this can't be used to enumerate addresses — and for an account
          // created through Google (no credential row) the reset CREATES one,
          // so "Forgot password?" doubles as "set a password".
          sendResetPassword: async ({ user, token }: { user: { email: string }; token: string }) => {
            const url = `${config.betterAuthUrl}/reset-password?token=${encodeURIComponent(token)}`;
            dispatchMail(
              "password reset",
              resetPasswordEmail({ to: user.email, url, validMinutes: RESET_TOKEN_TTL_SECONDS / 60 }),
            );
          },
          resetPasswordTokenExpiresIn: RESET_TOKEN_TTL_SECONDS,
          // A reset is what you do when you suspect someone else has the old
          // password; leaving their sessions alive would defeat it.
          revokeSessionsOnPasswordReset: true,
        }
      : {}),
  },
  ...(mailerOn
    ? {
        emailVerification: {
          // Sent on sign-up; clicking marks `emailVerified` and lands on our
          // branded confirmation page. Soft for now (see requireEmailVerification).
          sendOnSignUp: true,
          sendVerificationEmail: async ({ user, token }: { user: { email: string }; token: string }) => {
            const callback = `${config.betterAuthUrl}/email-verified`;
            const url = `${config.betterAuthUrl}/api/auth/verify-email?token=${encodeURIComponent(
              token,
            )}&callbackURL=${encodeURIComponent(callback)}`;
            dispatchMail("email verification", verifyEmailEmail({ to: user.email, url }));
          },
        },
      }
    : {}),
  ...(socialProviders ? { socialProviders } : {}),
  account: {
    // Identity is the email: signing in with Google links to an existing
    // email+password account with the same address (and vice-versa) instead of
    // forking a second account. Google is trusted because it returns a verified
    // email, so we know the person signing in really owns the address.
    accountLinking: {
      enabled: true,
      trustedProviders: ["google"],
      // Better Auth defaults this to TRUE, which quietly made the linking above
      // dead code for every account we have. It refuses to link unless the
      // *local* row already has `emailVerified`, and nothing here ever sets it:
      // `requireEmailVerification` is false (no email round-trip in the MVP), so
      // every password sign-up lands with `emailVerified = false` — permanently.
      // The symptom is `account_not_linked` on the Google callback for anyone
      // who first signed up with a password; only users created THROUGH Google
      // could use Google, because they had nothing to link.
      //
      // The check exists to stop this: with no verification at sign-up, someone
      // can register an address they don't own, and linking then joins the real
      // owner to the squatter's account instead of locking them out. We accept
      // that here because the squat is already possible without linking, and
      // because Google having verified the address is the strongest signal we
      // have. The real fix is email verification at sign-up — until that ships,
      // this is a knowingly-taken trade, not an oversight.
      requireLocalEmailVerified: false,
    },
    // Desktop OAuth runs the Google consent in the system browser while the app
    // (a Tauri webview) initiated /sign-in/social from a *different* cookie jar,
    // so the signed `state` cookie set at sign-in is absent at the callback.
    // State + PKCE still live server-side in the verification table (default
    // storeStateStrategy "database"), single-use and short-lived, so we skip
    // only the redundant cookie check — the same thing Better Auth's own
    // oauth-proxy plugin does for cross-origin flows.
    skipStateCookieCheck: true,
  },
  plugins: [
    bearer(),
    organization({
      creatorRole: "owner",
      invitationExpiresIn: config.invitationExpiresInSeconds, // 48h
      // Inviting an address that is already pending re-sends instead of
      // failing with "already invited": the old row is canceled and a fresh
      // one (new id, new 48h) goes out. That is what an admin clicking Invite
      // a second time means.
      cancelPendingInvitationsOnReInvite: true,
      ...(mailerOn
        ? {
            // The invitation email (issue #99). Links to our public landing
            // page, which bounces into the desktop app's `baalda://invite/…`
            // deep link; the app then signs the person in (or up) with the
            // invited address and accepts. Better Auth awaits this callback,
            // so the send itself is fire-and-forget (`dispatchMail`).
            sendInvitationEmail: async (data: {
              id: string;
              email: string;
              role: string;
              organization: { name: string };
              invitation: { expiresAt: Date };
              inviter: { user: { name?: string | null; email: string } };
            }) => {
              const url = `${config.betterAuthUrl}/invite/${encodeURIComponent(data.id)}`;
              dispatchMail(
                "invitation",
                invitationEmail({
                  to: data.email,
                  url,
                  organizationName: data.organization.name,
                  inviterName: data.inviter.user.name?.trim() || data.inviter.user.email,
                  role: data.role,
                  expiresAt: new Date(data.invitation.expiresAt),
                }),
              );
            },
          }
        : {}),
      // Free-tier enforcement (spec: subscription billing). These run inside
      // Better Auth's create-organization / create-invitation endpoints and
      // throw an APIError with statusCode 402 whose message carries the
      // contract token ("vault_limit_reached" / "member_limit_reached").
      // The desktop keys off HTTP 402 + the token; a no-op when billing is off
      // (the entitlement helpers short-circuit to "allowed").
      organizationHooks: {
        beforeCreateOrganization: async (data) => {
          const { allowed, limit } = await canCreateOrganization(data.user.id);
          if (!allowed) {
            throw new APIError("PAYMENT_REQUIRED", {
              message: "vault_limit_reached",
              error: "vault_limit_reached",
              limit,
            });
          }
        },
        beforeCreateInvitation: async (data) => {
          // A re-invite replaces a pending row rather than adding a seat, so it
          // must pass even at the cap — otherwise a full free vault could never
          // re-send a lost invitation.
          if (await hasPendingInvitation(data.organization.id, data.invitation.email)) return;
          const { allowed, limit } = await canAddMember(data.organization.id);
          if (!allowed) {
            throw new APIError("PAYMENT_REQUIRED", {
              message: "member_limit_reached",
              error: "member_limit_reached",
              limit,
            });
          }
        },
        // A teammate accepted an invitation → announce to everyone live in the
        // vault so their roster refreshes and the join celebration fires.
        // (The join-code path bypasses Better Auth and announces itself; org
        // creation adds the owner via `afterAddMember`, which we deliberately
        // don't hook — no one should be "welcomed" to their own new vault.)
        afterAcceptInvitation: async (data) => {
          const name = data.user.name?.trim() || data.user.email;
          await announceMemberJoined(data.organization.id, name);
        },
        // Role changes must go through PATCH /api/orgs/:orgId/members/:userId,
        // which enforces our stricter matrix (an admin may not touch another
        // admin) and force-closes live sockets so the new role applies now.
        // Better Auth's own update-member-role endpoint does neither, so it's
        // closed off entirely.
        beforeUpdateMemberRole: async () => {
          throw new APIError("FORBIDDEN", {
            message: "role_change_not_supported_here",
          });
        },
      },
    }),
    // OAuth 2.1 authorization server for MCP clients (spec: MCP integration).
    // Lets a Claude "custom connector" run the standard discovery → dynamic
    // client registration → PKCE authorize/consent → token flow against an
    // EXISTING Baalda account. The issued access token carries the user id, so
    // POST /api/mcp resolves it to that user + the vault they picked on the
    // consent screen and enforces the very same per-file ACL an mcp_ token does.
    //
    // loginPage/consentPage are branded HTML we serve ourselves (see
    // routes/oauth-connect.ts) so the whole flow works on a headless server
    // (api.baalda.com) and any self-hoster, with no separate web frontend.
    mcp({
      // Canonical resource id advertised in the protected-resource metadata:
      // the MCP endpoint clients actually POST to.
      resource: `${config.betterAuthUrl}/api/mcp`,
      loginPage: `${config.betterAuthUrl}/oauth/login`,
      oidcConfig: {
        // loginPage is duplicated here only to satisfy OIDCOptions' type; the
        // mcp plugin overrides it with the top-level `loginPage` above.
        loginPage: `${config.betterAuthUrl}/oauth/login`,
        consentPage: `${config.betterAuthUrl}/oauth/consent`,
      },
    }),
  ],
});

export type Auth = typeof auth;
